name: smartdns
services:
  smartdns:
    image: ${SMARTDNS_IMAGE:-pymumu/smartdns:latest}
    hostname: smartdns
    container_name: smartdns
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${SMARTDNS_CONFIG_DIR:-/etc/smartdns}:/etc/smartdns
