name: seafile-init
services:
  init:
    container_name: seafile-init
    image: tianon/true
    networks:
      seafile:
        ipv4_address: ${NET_ADDR_INIT_IPV4:-172.18.41.254}

networks:
  seafile:
    name: seafile
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-seafile
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: ${NET_MTU:-1500}
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-172.18.41.0/24}
        - subnet: ${NET_CIDR_IPV6:-fd00:172:18:41::/64}
