name: cloudflare-ddns
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    hostname: cloudflare-ddns
    container_name: cloudflare-ddns
    restart: unless-stopped
    network_mode: host
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DDNS_CONFIG_FILE:-/etc/cloudflare-ddns/config.json}:/config.json
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
