name: caddy
services:
  caddy:
    image: caddy:2.9
    hostname: caddy
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # HTTP/3
      - 443:443/udp
    environment:
      CADDY_CF_API_TOKEN: ${CADDY_CF_API_TOKEN:?}
    volumes:
      - ${CADDY_CONFIG_FILE:-/etc/caddy/Caddyfile}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
