name: traepot-init
services:
  init:
    container_name: traepot-init
    image: tianon/true
    networks:
      traepot:
        ipv4_address: ${NET_ADDR_INIT_IPV4:-172.18.1.254}

networks:
  traepot:
    name: traepot
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-traepot
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: ${NET_MTU:-1500}
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-172.18.1.0/24}
        - subnet: ${NET_CIDR_IPV6:-fd00:172:18:1::/64}
