name: traepot-app
services:
  traefik:
    image: traefik:latest
    hostname: traefik
    container_name: traepot-traefik
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      potnet:
        ipv4_address: ${NET_ADDR_TRAEFIK_IPV4:-172.18.1.2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ${TRAEPOT_TRAEFIK_CONFIG_DIR:-/etc/traepot/traefik}:/etc/traefik
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --log.level=INFO
      - --log.format=json
      - --accesslog=true
      - --accesslog.format=json
      # traefik-get-real-ip
      - --experimental.plugins.cloudflarewarp.modulename=github.com/Paxxs/traefik-get-real-ip
      - --experimental.plugins.cloudflarewarp.version=v1.0.2
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3

  coredns:
    image: coredns/coredns:latest
    hostname: coredns
    container_name: traepot-coredns
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      potnet:
        ipv4_address: ${NET_ADDR_COREDNS_IPV4:-172.18.1.3}
    volumes:
      - ${TRAEPOT_COREDNS_CONFIG_FILE:-/etc/traepot/Corefile}:/Corefile
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3

networks:
  potnet:
    name: potnet
    external: true
