name: nsvc-init
services:
  init:
    container_name: nsvc-init
    image: tianon/true
    networks:
      easytier: null
      nsvc:
        ipv4_address: ${NET_ADDR_INIT_IPV4:-7.19.0.254}

networks:
  easytier:
    name: easytier
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-et
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1380"
    ipam:
      config:
        - subnet: 172.18.11.0/24
        - subnet: fd00:172:18:11::/64
  nsvc:
    name: nsvc
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-nsvc
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: ${NET_MTU:-1500}
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-7.19.0.0/24}
        - subnet: ${NET_CIDR_IPV6:-fd00:7:19:0::/64}
