name: nsvc-side-easytier
services:
  nsvc-side-easytier:
    image: ${EASYTIER_IMAGE:-easytier/easytier:latest}
    hostname: ${EASYTIER_HOSTNAME:-easytier}
    container_name: nsvc-side-easytier
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      easytier:
        gw_priority: 10
      nsvc: null
    ports:
      - 11001:11001
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
    command: -w ${EASYTIER_CONFIG_SERVER:-udp://config-server.easytier.cn:22020/admin}

networks:
  easytier:
    name: easytier
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-et
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1380"
    ipam:
      config:
        - subnet: 172.18.11.0/24
        - subnet: fd00:172:18:11::/64
  nsvc:
    name: nsvc
    external: true
