name: filebrowser
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    hostname: filebrowser
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${FILE_BROWSER_SRV_DIR:-/data/filebrowser}:/srv
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
