name: filebrowser-host
services:
  filebrowser-server:
    image: ${FILE_BROWSER_SERVER_IMAGE:-filebrowser/filebrowser:latest}
    hostname: filebrowser-server
    container_name: filebrowser-server
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${FILE_BROWSER_SERVE_DIR:-/data/filebrowser/srv}:/srv
      - ${FILE_BROWSER_DATA_DB:-/data/filebrowser/filebrowser.db}:/database.db
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
