name: filebrowser-app
services:
  filebrowser-server:
    image: ${FILE_BROWSER_SERVER_IMAGE:-filebrowser/filebrowser:latest}
    hostname: filebrowser-server
    container_name: filebrowser-server
    restart: unless-stopped
    networks:
      filebrowser:
        ipv4_address: ${NET_ADDR_SERVER_IPV4:-172.18.40.10}
    volumes:
      - ${FILE_BROWSER_SERVE_DIR:-/data/filebrowser/srv}:/srv
      - ${FILE_BROWSER_DATA_DB:-/data/filebrowser/filebrowser.db}:/database.db
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb

networks:
  filebrowser:
    name: filebrowser
    external: true
