name: filebrowser-init
services:
  init:
    image: tianon/true
    container_name: filebrowser-init
    networks:
      filebrowser:
        ipv4_address: ${NET_ADDR_INIT_IPV4:-172.18.40.254}

networks:
  filebrowser:
    name: filebrowser
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-fb
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-172.18.40.0/24}
