name: rabbitmq
services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - ${RABBITMQ_PORT:-5672}:5672
      - ${RABBITMQ_MGMT_PORT:-15672}:15672
    volumes:
      - ${RABBITMQ_DATA_DIR:-/data/rabbitmq}:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-root}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:?error}
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
