name: yahs-iperf3
services:
  yahs-iperf3:
    image: ${IPERF3_IMAGE:-mlabbe/iperf3:latest}
    hostname: yahs-iperf3
    container_name: yahs-iperf3
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${IPERF3_CONFIG_DIR:-/etc/iperf3}:/etc/iperf3:ro
    command: >-
      -s
      -p ${IPERF3_PORT:-15201}
      --idle-timeout 10
      --use-pkcs1-padding
      --authorized-users-path ${IPERF3_CONFIG_DIR:-/etc/iperf3}/users.csv
      --rsa-private-key-path ${IPERF3_CONFIG_DIR:-/etc/iperf3}/private_key.pem

    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "${IPERF3_PORT:-15201}"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${IPERF3_MEM_LIMIT:-128}mb
