name: derper
services:
  derper:
    image: 1itt1eb0y/derper:latest
    hostname: derper
    container_name: derper
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DERPER_CERTS_DIR:-./certs}:/app/certs
    command: >-
      -hostname "${DERPER_HOSTNAME}"
      -certmode manual
      -certdir /app/certs
      -a :${DERPER_DERP_PORT:-443}
      -stun=${DERPER_STUN_FLAG:-false}
      -http-port -1
