name: headscale
services:
  headscale:
    image: headscale/headscale:0.25
    hostname: headscale
    container_name: headscale
    restart: unless-stopped
    network_mode: host
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ${HEADSCALE_CONFIG_DIR:-/etc/headscale}:/etc/headscale
      - ${HEADSCALE_DATA_DIR:-/var/lib/headscale}:/var/lib/headscale
    command: serve

  headscale-admin:
    image: goodieshq/headscale-admin:0.25
    hostname: headscale-admin
    container_name: headscale-admin
    restart: unless-stopped
    depends_on:
      - headscale

  headscale-caddy:
    image: caddy:2.8
    hostname: headscale-caddy
    container_name: headscale-caddy
    restart: unless-stopped
    ports:
      - 8088:8088
      - 8088:8088/udp
    volumes:
      - ${HEADSCALE_CADDY_CONFIG_FILE:-/etc/headscale/caddy/Caddyfile}:/etc/caddy/Caddyfile
      - headscale-caddy-data:/data
      - headscale-caddy-config:/config
    depends_on:
      - headscale-admin

volumes:
  headscale-caddy-data:
  headscale-caddy-config:
