name: headscale-app
services:
  headscale:
    image: headscale/headscale:0.25
    hostname: headscale
    container_name: headscale
    restart: unless-stopped
    networks:
      headscale:
        ipv4_address: 172.18.10.2
    ports:
      - 0.0.0.0:3478:3478/udp
    volumes:
      - ${HEADSCALE_CONFIG_DIR:-/etc/headscale}:/etc/headscale
      - headscale-data:/var/lib/headscale
    command: serve

  headscale-admin:
    image: goodieshq/headscale-admin:0.25
    hostname: headscale-admin
    container_name: headscale-admin
    restart: unless-stopped
    networks:
      headscale:
        ipv4_address: 172.18.10.3
    depends_on:
      - headscale

networks:
  headscale:
    name: headscale
    external: true

volumes:
  headscale-data:
    name: headscale-data
    external: true
