name: headscale-app
services:
  headscale:
    image: headscale/headscale
    hostname: headscale
    container_name: headscale
    restart: unless-stopped
    ports:
      - 8080:8080
      - 127.0.0.1:9090:9090
    volumes:
      - ${HEADSCALE_CONFIG_DIR:-/etc/headscale}:/etc/headscale
      - ${HEADSCALE_DATA_DIR:-/var/lib/headscale}:/var/lib/headscale
    command: serve
