name: headscale
services:
  headscale:
    image: headscale/headscale:0.25
    hostname: headscale
    container_name: headscale
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9090:9090
    volumes:
      - ${HEADSCALE_CONFIG_DIR:-/etc/headscale}:/etc/headscale
      - ${HEADSCALE_DATA_DIR:-/var/lib/headscale}:/var/lib/headscale
    command: serve
  headscale-admin:
    image: goodieshq/headscale-admin:0.25
    hostname: headscale-admin
    container_name: headscale-admin
    restart: unless-stopped
