name: nginx-sni-proxy
services:
  nginx-sni-proxy:
    image: ${NGINX_IMAGE:-nginx:latest}
    hostname: ${NGINX_HOSTNAME:-nginx-sni-proxy}
    container_name: nginx-sni-proxy
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      sni-proxy: null
    volumes:
      - ${NGINX_CONF_FILE:-/etc/sni/nginx.conf}:/etc/nginx.conf

networks:
  sni-proxy:
    name: sni-proxy
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-sni
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: ${NET_ADDR_GATEWAY_IPV4:-7.19.0.1}
      com.docker.network.driver.mtu: ${NET_MTU:-1380}
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-7.19.0.0/24}
        - subnet: ${NET_CIDR_IPV6:-fd00:7:19:0::/64}
