name: nginx
services:
  nginx:
    image: ${NGINX_IMAGE:-nginx:latest}
    hostname: nginx
    container_name: nginx
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${NGINX_CONF_FILE:-/etc/nginx.conf}:/etc/nginx.conf
