name: easybird
services:
  easybird:
    image: ${EASYBIRD_IMAGE:-ghcr.io/detavern/easybird:latest}
    hostname: ${EASYBIRD_HOSTNAME:-easybird}
    container_name: easybird
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      easybird:
        ipv4_address: 172.18.18.18
        ipv6_address: fd00:172:18:18::18/64
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
      - EASYTIER_CONFIG_SERVER=${EASYTIER_CONFIG_SERVER:?}
      - BIRD_ROUTER_ID=${BIRD_ROUTER_ID:?}
      - BIRD_STATIC_IPV6_ENABLED=0
      - BIRD_OSPF_V3_ENABLED=0
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/bird:/etc/bird
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${EASYBIRD_MEM_LIMIT:-256}mb

networks:
  easybird:
    name: easybird
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-easybird
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1380"
    ipam:
      config:
        - subnet: 172.18.18.0/24
        - subnet: fd00:172:18:18::/64
