name: easybird
services:
  easybird:
    image: ${EASYBIRD_IMAGE:-ghcr.io/detavern/easybird:latest}
    hostname: ${EASYBIRD_HOSTNAME:-easybird}
    container_name: easybird
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
      - EASYTIER_CONFIG_SERVER=${EASYTIER_CONFIG_SERVER:?}
      - BIRD_ROUTER_ID=${BIRD_ROUTER_ID:?}
      - BIRD_STATIC_IPV6_ENABLED=0
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/bird:/etc/bird
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${EASYBIRD_MEM_LIMIT:-256}mb
