name: yahs-easybird
services:
  yahs-easybird:
    image: ${EASYBIRD_IMAGE:-ghcr.io/detavern/easybird:latest}
    hostname: yahs-easybird
    container_name: yahs-easybird
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
      - EASYTIER_CONFIG_SERVER=${EASYTIER_CONFIG_SERVER:?}
      - EASYTIER_EXTRA_OPTIONS=${EASYTIER_EXTRA_OPTIONS:-}
      - BIRD_ROUTER_ID=${BIRD_ROUTER_ID:?}
      - BIRD_STATIC_IPV6_ENABLED=0
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${BIRD_CONFIG_DIR:-/etc/bird}:/etc/bird
      - ${EASYTIER_LOCAL_STATE_DIR:-/data/easybird/state}:/root/.local/share/easytier

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    deploy:
      resources:
        limits:
          memory: ${EASYBIRD_MEM_LIMIT:-256}mb
