name: mysql
services:
  mysql:
    image: mysql:8
    hostname: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ${MYSQL_DATA_DIR:-/data/mysql}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-}
      MYSQL_USER: ${MYSQL_USER:-}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
