name: yahs-mysql
services:
  yahs-mysql:
    image: mysql:8
    hostname: yahs-mysql
    container_name: yahs-mysql
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${MYSQL_DATA_DIR:-/data/yahs/mysql}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-}
      MYSQL_USER: ${MYSQL_USER:-}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          memory: 1024mb
