name: xboard-app-init
services:
  xboard-app-init:
    image: ghcr.io/cedar2025/xboard:new
    container_name: xboard-app-init
    networks:
      xboard:
    environment:
      - docker=true
      - ENABLE_SQLITE=true
      - ENABLE_REDIS=true
      - ADMIN_ACCOUNT=${XBOARD_ADMIN_ACCOUNT:-admin@example.com}
    volumes:
      - xboard-redis-data:/data/redis
      - xboard-sqlite-data:/www/.docker/.data
      - ${XBOARD_APP_ENV:-/data/xboard/env}:/www/.env
      - ${XBOARD_APP_DATA_STORAGE:-/data/xboard/storage}:/www/storage
      - ${XBOARD_APP_DATA_PLUGINS:-/data/xboard/plugins}:/www/plugins
    command: php artisan xboard:install

networks:
  xboard:
    name: xboard
    external: true

volumes:
  xboard-redis-data:
    name: xboard-redis-data
    external: true
  xboard-sqlite-data:
    name: xboard-sqlite-data
    external: true
