name: xboard-init
services:
  app-init:
    image: ghcr.io/cedar2025/xboard:new
    container_name: xboard-app-init
    networks:
      xboard:
    environment:
      - docker=true
    volumes:
      - xboard-redis-data:/data
      - xboard-sqlite-data:/www/.docker/.data
      - ${XBOARD_APP_ENV:-/data/xboard/env}:/www/.env
      - ${XBOARD_APP_DATA_STORAGE:-/data/xboard/storage}:/www/storage
      - ${XBOARD_APP_DATA_PLUGINS:-/data/xboard/plugins}:/www/plugins
    command: php artisan xboard:install

networks:
  xboard:
    name: xboard
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-xboard
    ipam:
      config:
        - subnet: 172.18.41.0/24

volumes:
  xboard-redis-data:
    name: xboard-redis-data
  xboard-sqlite-data:
    name: xboard-sqlite-data
