name: xboard-app
services:
  xboard-app-web:
    image: ghcr.io/cedar2025/xboard:new
    hostname: xboard-app-web
    container_name: xboard-app-web
    restart: unless-stopped
    networks:
      xboard:
        ipv4_address: ${NET_ADDR_APP_WEB_IPV4:-172.18.41.10}
    environment:
      - docker=true
    volumes:
      - ${XBOARD_DATA_DIR:-/data/xboard/docker}/redis:/data
      - ${XBOARD_DATA_DIR:-/data/xboard/docker}:/www/.docker/.data
      - ${XBOARD_APP_ENV:-/data/xboard/env}:/www/.env
      - ${XBOARD_APP_DATA_STORAGE:-/data/xboard/storage}:/www/storage
      - ${XBOARD_APP_DATA_PLUGINS:-/data/xboard/plugins}:/www/plugins
    command: php artisan octane:start --host=0.0.0.0 --port=7001
  xboard-app-horizon:
    image: ghcr.io/cedar2025/xboard:new
    hostname: xboard-app-horizon
    container_name: xboard-app-horizon
    restart: unless-stopped
    networks:
      xboard:
    volumes:
      - ${XBOARD_DATA_DIR:-/data/xboard/docker}/.docker/.data/redis:/data
      - ${XBOARD_DATA_DIR:-/data/xboard/docker}:/www/.docker/.data
      - ${XBOARD_APP_ENV:-/data/xboard/env}:/www/.env
      - ${XBOARD_APP_DATA_STORAGE:-/data/xboard/storage}:/www/storage
      - ${XBOARD_APP_DATA_PLUGINS:-/data/xboard/plugins}:/www/plugins
    command: php artisan horizon

networks:
  xboard:
    name: xboard
    external: true
