name: xboard-init
services:
  init:
    image: tianon/true
    container_name: xboard-init
    networks:
      xboard:

networks:
  xboard:
    name: xboard
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-xboard
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-172.18.41.0/24}
