name: unifi-app
services:
  unifi-app:
    image: lscr.io/linuxserver/unifi-network-application:latest
    hostname: unifi-app
    container_name: unifi-app
    restart: unless-stopped
    networks:
      unifi:
    volumes:
      - unifi-app-config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # mongo connection
      - MONGO_USER=${UNIFI_MONGO_USERNAME:-unifi}
      - MONGO_PASS=${UNIFI_MONGO_PASSWORD:?}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=${UNIFI_MONGO_DATABASE:-unifi}
      - MONGO_AUTHSOURCE=${MONGO_INITDB_DATABASE:-admin}
      # java memory limit
      - MEM_STARTUP=256
      - MEM_LIMIT=1024
    ports:
      - 3478:3478/udp
      - 5514:5514/udp
      - 6789:6789
      - 8080:8080
      - 8843:8843
      - 8443:8443
      # login page
      - 8880:8880/tcp
      - 10001:10001/udp
    deploy:
      resources:
        limits:
          memory: 1200mb
    depends_on:
      unifi-db:
        condition: service_healthy
        restart: true
  unifi-db:
    image: mongo:7
    hostname: unifi-db
    container_name: unifi-db
    restart: unless-stopped
    networks:
      unifi:
    volumes:
      - unifi-db-data:/data/db
      # mount scripts
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      # root
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      # user created by script
      INIT_SCRIPT_USERNAME: ${UNIFI_MONGO_USERNAME:-unifi}
      INIT_SCRIPT_PASSWORD: ${UNIFI_MONGO_PASSWORD:?}
      INIT_SCRIPT_DATABASE: ${UNIFI_MONGO_DATABASE:-unifi}
    command:
      # Limit the wired tiger cache size to 256MB
      - --wiredTigerCacheSizeGB
      - ${MONGO_WIRED_TIGER_CACHE_SIZE:-0.25}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
networks:
  unifi:
    name: unifi
    external: true
volumes:
  unifi-db-data:
    name: unifi-db-data
    external: true
  unifi-app-config:
    name: unifi-app-config
    external: true
