name: unifi-app
services:
  unifi-app:
    image: lscr.io/linuxserver/unifi-network-application:latest
    hostname: unifi-app
    container_name: unifi-app
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      unifi:
        ipv4_address: ${NET_ADDR_SERVER_IPV4:-172.18.21.10}
    ports:
      - 3478:3478/udp
      - 5514:5514/udp
      - 6789:6789
      # inform
      - 8080:8080
      - 8843:8843
      - 8443:8443
      # login page
      - 8880:8880/tcp
      - 10001:10001/udp
    volumes:
      - unifi-app-config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # mongo connection
      - MONGO_USER=${UNIFI_MONGO_USERNAME:-unifi}
      - MONGO_PASS=${UNIFI_MONGO_PASSWORD:?}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=${UNIFI_MONGO_DATABASE:-unifi}
      - MONGO_AUTHSOURCE=${MONGO_INITDB_DATABASE:-admin}
      # java memory limit
      - MEM_STARTUP=256
      - MEM_LIMIT=1024
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1200mb

networks:
  unifi:
    name: unifi
    external: true

volumes:
  unifi-app-config:
    name: unifi-app-config
    external: true
