name: unifi-init
services:
  init:
    container_name: unifi-init
    image: tianon/true
    networks:
      unifi:
volumes:
  unifi-db-data:
    name: unifi-db-data
  unifi-app-config:
    name: unifi-app-config
networks:
  unifi:
    name: unifi
    driver: bridge
