name: pot-hubproxy
services:
  hubproxy:
    image: ${HUBPROXY_IMAGE:-ghcr.io/sky22333/hubproxy:latest}
    hostname: hubproxy
    container_name: pot-hubproxy
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.middlewares.cloudflare-realip.plugin.realip.Proxy[0].proxyHeadername="*"
      - traefik.http.middlewares.cloudflare-realip.plugin.realip.Proxy[0].realIP=CF-Connecting-IP
      - traefik.http.middlewares.cloudflare-realip.plugin.realip.Proxy[0].OverwriteXFF=true
      - traefik.http.routers.hubproxy.rule=Host(`hubproxy.pot`)
      - traefik.http.routers.hubproxy.entrypoints=web
      - traefik.http.routers.hubproxy.middlewares=cloudflare-realip@docker
      - traefik.http.services.hubproxy.loadbalancer.server.port=5000
      - traefik.http.services.hubproxy.loadbalancer.passhostheader=true
      - traefik.http.services.hubproxy.loadbalancer.healthcheck.path=/
    restart: unless-stopped
    networks:
      - potnet
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb

networks:
  potnet:
    name: potnet
    external: true
