name: easytier
services:
  easytier:
    # 国内可以使用 m.daocloud.io/docker.io/easytier/easytier:latest
    image: easytier/easytier:latest
    hostname: easytier
    container_name: easytier
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${EASYTIER_CONFIG_DIR:-/etc/easytier}:/etc/easytier
    command: -c /etc/easytier/config.toml
