name: easytier-web
services:
  easytier-web:
    image: easytier/easytier:latest
    hostname: easytier-web
    container_name: easytier-web
    restart: unless-stopped
    networks:
      easytier:
        ipv4_address: 172.18.11.3
    ports:
      - 0.0.0.0:22020:22020/udp
    volumes:
      - easytier-web-data:/data
    entrypoint: tini -- easytier-web
    command: -d /data/et.db --console-log-level warn

networks:
  easytier:
    name: easytier
    external: true

volumes:
  easytier-web-data:
    name: easytier-web-data
