name: easytier-web
services:
  easytier-web:
    image: ${EASYTIER_IMAGE:-easytier/easytier:latest}
    hostname: easytier-web
    container_name: easytier-web
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      easytier:
        ipv4_address: 172.18.11.3
    ports:
      - 0.0.0.0:22020:22020
      - 0.0.0.0:22020:22020/udp
    volumes:
      - easytier-web-data:/data
    entrypoint: tini -- easytier-web
    command: -d /data/et.db --console-log-level warn
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${EASYTIER_MEM_LIMIT:-256}mb

networks:
  easytier:
    name: easytier
    external: true

volumes:
  easytier-web-data:
    name: easytier-web-data
