name: easytier
services:
  easytier:
    image: ${EASYTIER_IMAGE:-easytier/easytier:latest}
    hostname: ${EASYTIER_HOSTNAME:-easytier}
    container_name: easytier
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
    command: -w ${EASYTIER_CONFIG_SERVER:-udp://config-server.easytier.cn:22020/admin}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${EASYTIER_MEM_LIMIT:-256}mb
