name: easytier
services:
  easytier:
    # 国内可以使用 m.daocloud.io/docker.io/easytier/easytier:latest
    image: easytier/easytier:latest
    hostname: ${EASYTIER_HOSTNAME:-easytier}
    container_name: easytier
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    command: -w ${EASYTIER_CONFIG_SERVER:-udp://config-server.easytier.cn:22020/admin}
