name: easytier-init
services:
  init:
    container_name: easytier-init
    image: tianon/true
    networks:
      easytier:
        ipv4_address: 172.18.11.254

networks:
  easytier:
    name: easytier
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker-et
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: "1500"
    ipam:
      config:
        - subnet: 172.18.11.0/24
