name: easytier
services:
  easytier:
    image: ${EASYTIER_IMAGE:-easytier/easytier:latest}
    hostname: ${EASYTIER_HOSTNAME:-easytier}
    container_name: easytier
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${EASYTIER_CONFIG_DIR:-/etc/easytier}:/etc/easytier
    command: -c /etc/easytier/config.toml
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: ${EASYTIER_MEM_LIMIT:-256}mb
    deploy:
      resources:
        limits:
          memory: ${WATCHTOWER_MEM_LIMIT:-128}mb