name: minio-init
services:
  init:
    container_name: minio-init
    image: tianon/true
    networks:
      minio:
        ipv4_address: ${NET_ADDR_INIT_IPV4:-172.18.42.254}

networks:
  minio:
    name: minio
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-minio
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.driver.mtu: ${NET_MTU:-1500}
    ipam:
      config:
        - subnet: ${NET_CIDR_IPV4:-172.18.42.0/24}
        - subnet: ${NET_CIDR_IPV6:-fd00:172:18:42::/64}
