name: postgres
services:
  postgres:
    image: postgres:18
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    # set shared memory limit, half of the total memory limit is a good practice
    shm_size: 256mb
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ${POSTGRES_DATA_DIR:-/data/postgresql}:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
