name: yahs-postgres
services:
  yahs-postgres:
    image: postgres:18
    hostname: yahs-postgres
    container_name: yahs-postgres
    restart: unless-stopped
    network_mode: host
    # set shared memory limit, half of the total memory limit is a good practice
    shm_size: 512mb
    volumes:
      - ${POSTGRES_DATA_DIR:-/data/yahs/postgresql}:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}

    healthcheck:
      test:
        - CMD
        - wget
        - -qO-
        - http://127.0.0.1:${HUBPROXY_LISTEN_PORT:-5000}/ready
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: 3
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEM_LIMIT:-1024}mb
