name: mongo
services:
  mongo:
    image: mongo:7
    hostname: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - ${MONGO_PORT:-27017}:27017
    volumes:
      - ${MONGO_DATA_VOL:-/data/mongo}:/data/db
      # mount scripts
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      # root
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      # user created by script
      INIT_SCRIPT_USERNAME: ${INIT_SCRIPT_USERNAME:-user}
      INIT_SCRIPT_PASSWORD: ${INIT_SCRIPT_PASSWORD:?}
      INIT_SCRIPT_DATABASE: ${INIT_SCRIPT_DATABASE:?}
    command:
      # Limit the wired tiger cache size to 256MB
      - --wiredTigerCacheSizeGB
      - ${MONGO_WIRED_TIGER_CACHE_SIZE:-0.25}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512mb
