name: easytier-bird
services:
  easytier-bird:
    image: ghcr.io/detavern/easytier-bird:latest
    hostname: ${EASYTIER_HOSTNAME:-easytier-bird}
    container_name: easytier-bird
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
    networks:
      easytier:
        ipv4_address: 172.18.11.11
        ipv6_address: fd00:172:18:11::11/64
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=Asia/Shanghai
      - EASYTIER_CONFIG_SERVER=${EASYTIER_CONFIG_SERVER:?}
      - BIRD_ROUTER_ID=${BIRD_ROUTER_ID:?}
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/bird/ospf:/etc/bird/ospf

networks:
  easytier:
    name: easytier
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.name: docker-et
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: 172.18.11.1
      com.docker.network.driver.mtu: "1380"
    ipam:
      config:
        - subnet: 172.18.11.0/24
        - subnet: fd00:172:18:11::/64
