name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - 
        name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/detavern/terminal
      - 
        name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          context: ./docker/terminal
          tags: ghcr.io/detavern/terminal:latest
          labels: ${{ steps.meta.outputs.labels }}
          push: true
