name: Docker Image CI for caddy-plus

on:
  push:
    branches: ["master"]
    paths:
      - "docker/caddy-plus/**"

  pull_request:
    branches: ["master"]
    paths:
      - "docker/caddy-plus/**"

  workflow_dispatch:
    inputs:
      tag:
        description: "The tag version you want to build"
        required: false
        default: "latest"
        type: string

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        if: steps.docker.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=ref,event=branch
            type=raw,value=latest
            type=raw,value=${{ inputs.tag }}
          images: ghcr.io/detavern/caddy-plus

      - name: Build and push Docker images
        if: steps.docker.outputs.changed == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          context: ./docker/caddy-plus
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
